# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build and upload artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Obtain the name of the repository for the output file
    - name: Setup environment variable
      run: echo "repo_name_hynix=$GITHUB_REPOSITORY"| sed 's+noobstersmc/++' >> $GITHUB_ENV
    # Setup Java 11
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Setup caching to make it faster
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    # Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # Pull the gradle.properties from the repo secrets
    - name: Restore gradle.properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        cat >> ~/.gradle/gradle.properties << EOL
        ${GRADLE_PROPERTIES}
        EOL
    # Build the project
    - name: Build with Gradle
      run: ./gradlew build
    # Publish to maven repository
    - name: Build with Gradle
      run: ./gradlew publish
    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.repo_name_hynix}}-JDk11
        path: build/libs
